### PR TITLE
Add some helper functions

### PR DESCRIPTION
**Pull request by develop331**
Add helper functions:
- print(T values...) - All values are separated by a space and a newline is inserted at the end
- input(string prompt, T* target) - Prints the prompt, waits for input, then puts the input where the target points
- int(string str) - Turns a string to int - `std::stoi`
- str(int num) - Turns an int to string - `std::to_string`
- REF(value) - macro - Adds the reference symbol before the value

Also allowed `str` to be replaced with `string` in type annotations as it was annoying me. The old annotation still works, as it just replaces `str` if found in the annotation string.

### CODE REVIEW

**Comment by develop331** [comment]
saw this, going to be useful for something i need to do soon, so will probably expand a bit more for struct, arrays and pointer support

**Comment by develop331** [comment]
Going to work on pointers/arrays now, don't merge yet please

**Comment by develop331** [comment]
Arrays/pointers done, feel free to test around and I'll make changes to it and edit documentation if needed

**Comment by harishtpj** [comment]
Everything looks good—merging now. Thanks for your contribution!

**Comment by develop331** [comment]
👍

**Pull request merged**
